// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fNnkpvbXvmxzat5b7zFjZn1F-E8SiWQ',
    appId: '1:895109510915:web:12b8490a408d6b45951b36',
    messagingSenderId: '895109510915',
    projectId: 'aliceworkshop4honkaistarrail',
    authDomain: 'aliceworkshop4honkaistarrail.firebaseapp.com',
    storageBucket: 'aliceworkshop4honkaistarrail.appspot.com',
    measurementId: 'G-NF0CSY40K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5bY_CBHTK3eKA1cg9WmFMl9bR74JdGZs',
    appId: '1:895109510915:android:432b13aa3072a210951b36',
    messagingSenderId: '895109510915',
    projectId: 'aliceworkshop4honkaistarrail',
    storageBucket: 'aliceworkshop4honkaistarrail.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEE29Kfh2M2hF6QqhO8h4tgW0Et9XWsao',
    appId: '1:895109510915:ios:7fc2d088308f36ce951b36',
    messagingSenderId: '895109510915',
    projectId: 'aliceworkshop4honkaistarrail',
    storageBucket: 'aliceworkshop4honkaistarrail.appspot.com',
    iosClientId: '895109510915-6vf0dsgj676319f4liajjeemgjp4r99u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hsrwikiproject',
  );
}
