on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter Web
        run: flutter build web --web-renderer canvaskit

      - name: Deploy to Git Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.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 }}
          publish_dir: ./build/web
          external_repository: never1andwxy/HSRwiki_WEB
          publish_branch: gh-pages