on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Clone GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: never1andwxy/HSRwiki_WEB
          ref: gh-pages
          path: gh-pages

      - name: Copy Flutter Web build
        run: |
          cp -R build/web/* gh-pages/

      - name: Commit and push to GitHub Pages repository
        run: |
          cd gh-pages
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "Deploy Flutter Web"
          git push
