on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter Web
        run: flutter build web --web-renderer canvaskit

      - name: Clone GitHub Pages repository
        uses: actions/checkout@v2
        with:
          repository: never1andwxy/HSRwiki_WEB
          ref: gh-pages
          path: gh-pages

                - name: Copy Flutter Web build
        run: |
          cp -R build/web/* gh-pages/

  

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Commit and push to GitHub Pages repository
        run: |
          cd gh-pages
          git add -A
          git commit -m "Deploy Flutter Web"
          git push