name: Package Release

on:
  workflow_dispatch:

jobs:
  version:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: get-version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        name: Get Version
        env:
          ENV_TAG: ${{ github.ref }}
        run: |
          echo "version=$(echo $ENV_TAG | sed 's/refs\/tags\/v//' | sed 's/+/./')" >> "$GITHUB_OUTPUT"
  package-windows:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: windows-package
    runs-on: windows-latest
    needs:
      - version
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.10.1'
          cache: true
      - name: Install project dependencies
        run: flutter pub get
      - name: Build Windows
        env:
          ENV_MS_STORE_PUBLISHER_NAME: ${{ secrets.MS_STORE_PUBLISHER_NAME }}
          ENV_MS_STORE_IDENTITY_NAME: ${{ secrets.MS_STORE_IDENTITY_NAME }}
          ENV_MS_STORE_PUBLISHER: ${{ secrets.MS_STORE_PUBLISHER }}
          ENV_VERSION: ${{ needs.version.outputs.version }}
        run: |
          dart run msix:create --publisher-display-name "$env:ENV_MS_STORE_PUBLISHER_NAME" --identity-name "$env:ENV_MS_STORE_IDENTITY_NAME" --publisher "$env:ENV_MS_STORE_PUBLISHER" --version "$env:ENV_VERSION"
      - uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: build\windows\runner\Release\hsrwikiproject.msix
  package-android:
    name: android-apk
    runs-on: windows-latest
    needs:
      - version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '17.x'
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.10.1'
          cache: true
      - name: Install project dependencies
        run: flutter pub get
      - name: Build Windows
        env:
          ENV_VERSION: ${{ needs.version.outputs.version }}
        run: |
          flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: create-release
    runs-on: ubuntu-latest
    needs:
      - version
      - package-windows
      - package-android
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: windows-package
          path: build
      - uses: actions/download-artifact@v3
        with:
          name: android-apk
          path: build
      - name: Rename File
        env:
          ENV_VERSION: ${{ needs.version.outputs.version }}
        run: |
          cp ./build/hsrwikiproject.msix ./build/hsrwikiproject-${ENV_VERSION}.msix
          cp ./build/app-release.apk ./build/hsrwikiproject-${ENV_VERSION}.apk
          tree ./build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          ENV_VERSION: ${{ needs.version.outputs.version }}
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          files: |
            ./build/hsrwikiproject-${{ needs.version.outputs.version }}.msix
            ./build/hsrwikiproject-${{ needs.version.outputs.version }}.apk
      - name: Commit to Wiki
        env:
          ENV_DEPLOY_KEY_WIKI: ${{ secrets.DEPLOY_KEY_WIKI }}
        run: |
          date
