name: Windows InnoSetup

on:
  workflow_dispatch:

jobs:
  build:
    name: windows-deploy
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.13.4'
          cache: true

      - name: Install project dependencies
        run: flutter pub get

      - name: Build
        run: |
          flutter build windows --obfuscate --split-debug-info=.\build\windows\runner\Debug
      - name: Inno Setup
        env:
          ENV_TAG: ${{ github.ref }}
        run: |
          tar zxvf tool\IS6.tar
          $APP_VERSION_LINE = Get-Content "pubspec.yaml" | Select-String -Pattern "^version: "
          $Env:APP_VERSION = $APP_VERSION_LINE.Line.split(" ")[1].replace("+", ".")
          echo "VERSION=$Env:APP_VERSION" >> $env:GITHUB_ENV
          IS6\iscc .\windows\setup\hsrwikiproject.iss /DMyAppVersion=$Env:APP_VERSION
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          generate_release_notes: false
          fail_on_unmatched_files: true
          files: |
            .\windows\setup\hsrwikiproject-${{ env.VERSION }}.exe
